# Generated by Django 2.2.6 on 2019-11-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='mturk_id',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
