# Generated by Django 2.2.6 on 2019-11-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version2', '0002_respondent_mturk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='browser',
            field=models.CharField(default='None', max_length=70),
        ),
    ]
