# Generated by Django 2.2.6 on 2019-12-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version2', '0003_respondent_browser'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='curr_q',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
