# Generated by Django 2.2.6 on 2019-12-28 01:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('version2', '0004_respondent_curr_q'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respondent',
            name='curr_q',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
