# Generated by Django 2.2.6 on 2020-01-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version2', '0005_auto_20191227_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondent',
            name='age',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='education',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='mturk_id',
        ),
        migrations.AddField(
            model_name='respondent',
            name='email',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='respondent',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
