# Generated by Django 2.2.6 on 2020-02-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version2', '0006_auto_20200109_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('username', models.CharField(default='anonymous', max_length=70)),
            ],
        ),
    ]
