# Generated by Django 2.2.6 on 2020-02-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version2', '0007_topscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='order',
            field=models.CharField(default='1 2 3 4 5 6 7 8 9 10 49 50 51 52 53 54 55 56 57 58', max_length=70),
        ),
    ]
